### Activation Functions:
- sigmoid 
- tanh 
- relu 
<br/> 
Helpful resource: http://cs231n.github.io/optimization-2/

In [8]:
import numpy as np
import math

In [71]:
def sigmoid(X, W):
    '''
    '''
    # Forward pass:
    D = W.dot(X)
    f = 1.0/(np.power(math.exp(1), D) + 1)
    
    # Backpropagation:
    dD = (1 - f) * f # gradient of dot variable (D)
    dX = W.T.dot(dD) # backprop into X
    dW = dD.dot(X.T) # backprop into W
    
    return  f, dX, dW

In [72]:
# Test:
# matrix-matrix multiply gradient
np.random.seed(100)
W = np.random.randn(5,10)
X = np.random.randn(10,3)
D = W.dot(X)

dD = np.random.randn(*D.shape) # same shape as D
dW = dD.dot(X.T)
dX = W.T.dot(dD)

sigmoid(X, W)

(array([[0.54029475, 0.03620454, 0.40074414],
        [0.34730656, 0.76744243, 0.32937905],
        [0.93432013, 0.73179928, 0.9496582 ],
        [0.27592704, 0.96527985, 0.9573579 ],
        [0.90257859, 0.05932879, 0.98914803]]),
 array([[-0.44251687,  0.15202309, -0.44074151],
        [-0.06873408,  0.30653362,  0.18602718],
        [-0.01183154, -0.13829986,  0.10514979],
        [ 0.1799951 , -0.03521037,  0.1062866 ],
        [ 0.67177537,  0.28820923,  0.43766789],
        [-0.08192977,  0.07122554,  0.10800825],
        [ 0.1305745 ,  0.04136289,  0.00871929],
        [-0.25513021,  0.37696627, -0.02960013],
        [-0.57928433, -0.28435   , -0.23057662],
        [-0.30366184, -0.13899163, -0.21764941]]),
 array([[-0.54000864, -0.07989055, -0.18967666, -0.2472814 , -0.33322183,
         -0.06116737, -0.23706975, -0.08616257,  0.66635193, -0.56961689],
        [-0.57506651, -0.05608096,  0.00995958, -0.35494997, -0.30493581,
          0.03532468, -0.42951949, -0.12846636,  0.52

In [42]:
def sigmoid1(x, w):
    ''' Computes and returns output of sigmoid fn (f), dx, dw
        Args:
            x: inputs
            w: weights
            Assume x and w are 1D vectors of the same dimension
    '''
    # Forward pass:
    dot = np.dot(x,w)
    f = 1.0/(1 + math.exp(-dot))
    
    # Backpropagation:
    ddot = (1 - f)*f  # gradient on dot variable
    dx = [i * ddot for i in w] # backprop into x
    dw = [i * ddot for i in x] # backprop into w
    
    return f, dx, dw

In [43]:
# TestL
w = [2,-3]
x = [-1, -2]

np.dot(x,w), 
f, dx, dw = sigmoid1(w,x)
f, dx, dw

(0.9820137900379085,
 [-0.017662706213291107, -0.035325412426582214],
 [0.035325412426582214, -0.05298811863987332])